#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if [ -f $KAHIP_INCLUDE_DIR/parhip_interface.h ] &&
   [ -f $KAHIP_LIB_DIR/libparhip_interface.so ]
then
    echo "    using KAHIP_LIB_DIR=$KAHIP_LIB_DIR"
    wmake $targetType
    ln -sf $KAHIP_LIB_DIR/lib* $FOAM_SITE_LIBBIN/
else
    echo "    skipping kahip decomposer: ParHIP not found under" \
         "        KAHIP_INCLUDE_DIR=$KAHIP_INCLUDE_DIR" \
         "        KAHIP_LIB_DIR=$KAHIP_LIB_DIR"
fi

#------------------------------------------------------------------------------
